service: hybris

package:
  individually: true
  exclude:
  - ./**

provider:
  name: openwhisk
  runtime: nodejs:10
  ignore_certs: true
  defaultService: hybris
  service: ${opt:service, self:provider.defaultService}

custom:
  npm-version: ${file(package.json):name}@${file(package.json):version}
  ow-package: ${opt:ow-package, self:custom.npm-version}

plugins:
- serverless-openwhisk
- serverless-webpack

resources:
  packages: ${file(../common/serverlessPackageConfig.js)}

functions:
  validateGetCartService:
    name: ${self:custom.ow-package}/validateGetCartService
    handler: lib/validations/carts.getById

  getCartService:
    name: ${self:custom.ow-package}/getCartService
    handler: lib/actions/carts.getById

  validateDeleteCartService:
    name: ${self:custom.ow-package}/validateDeleteCartService
    handler: lib/validations/carts.deleteById

  deleteCartService:
    name: ${self:custom.ow-package}/deleteCartService
    handler: lib/actions/carts.deleteById

  validatePostCartShippingAddressService:
    name: ${self:custom.ow-package}/validatePostCartShippingAddressService
    handler: lib/validations/shippingaddress.post

  postCartShippingAddressService:
    name: ${self:custom.ow-package}/postCartShippingAddressService
    handler: lib/actions/shippingaddress.post

  validateDeleteCartShippingAddressService:
    name: ${self:custom.ow-package}/validateDeleteCartShippingAddressService
    handler: lib/validations/shippingaddress.del

  deleteCartShippingAddressService:
    name: ${self:custom.ow-package}/deleteCartShippingAddressService
    handler: lib/actions/shippingaddress.del

  validateDeleteCartBillingAddressService:
    name: ${self:custom.ow-package}/validateDeleteCartBillingAddressService
    handler: lib/validations/billingaddress.del

  validatePostCartBillingAddressService:
    name: ${self:custom.ow-package}/validatePostCartBillingAddressService
    handler: lib/validations/billingaddress.post

  postCartBillingAddressService:
    name: ${self:custom.ow-package}/postCartBillingAddressService
    handler: lib/actions/billingaddress.post

  validateGetPaymentMethodsService:
    name: ${self:custom.ow-package}/validateGetPaymentMethodsService
    handler: lib/validations/paymentmethods.get

  getPaymentMethodsService:
    name: ${self:custom.ow-package}/getPaymentMethodsService
    handler: lib/actions/paymentmethods.get

  validatePostPaymentService:
    name: ${self:custom.ow-package}/validatePostPaymentService
    handler: lib/validations/payments.post

  postPaymentService:
    name: ${self:custom.ow-package}/postPaymentService
    handler: lib/actions/payments.post

  validateDeletePaymentService:
    name: ${self:custom.ow-package}/validateDeletePaymentService
    handler: lib/validations/payments.deleteById

  deletePaymentService:
    name: ${self:custom.ow-package}/deletePaymentService
    handler: lib/actions/payments.deleteById

  validatePostCartService:
    name: ${self:custom.ow-package}/validatePostCartService
    handler: lib/validations/carts.post

  postCartService:
    name: ${self:custom.ow-package}/postCartService
    handler: lib/actions/carts.post

  validatePostCartEntryService:
    name: ${self:custom.ow-package}/validatePostCartEntryService
    handler: lib/validations/entries.post

  postCartEntryService:
    name: ${self:custom.ow-package}/postCartEntryService
    handler: lib/actions/entries.post

  validatePutCartEntryService:
    name: ${self:custom.ow-package}/validatePutCartEntryService
    handler: lib/validations/entries.put

  putCartEntryService:
    name: ${self:custom.ow-package}/putCartEntryService
    handler: lib/actions/entries.put

  validateDeleteCartEntryService:
    name: ${self:custom.ow-package}/validateDeleteCartEntryService
    handler: lib/validations/entries.deleteById

  deleteCartEntryService:
    name: ${self:custom.ow-package}/deleteCartEntryService
    handler: lib/actions/entries.deleteById

  validatePostCouponService:
    name: ${self:custom.ow-package}/validatePostCouponService
    handler: lib/validations/coupons.post

  postCouponService:
    name: ${self:custom.ow-package}/postCouponService
    handler: lib/actions/coupons.post

  validateDeleteCouponService:
    name: ${self:custom.ow-package}/validateDeleteCouponService
    handler: lib/validations/coupons.deleteById

  deleteCouponService:
    name: ${self:custom.ow-package}/deleteCouponService
    handler: lib/actions/coupons.deleteById

  validateGetShippingMethodsService:
    name: ${self:custom.ow-package}/validateGetShippingMethodsService
    handler: lib/validations/shippingmethods.get

  getShippingMethodsService:
    name: ${self:custom.ow-package}/getShippingMethodsService
    handler: lib/actions/shippingmethods.get

  validatePostShippingMethodService:
    name: ${self:custom.ow-package}/validatePostShippingMethodService
    handler: lib/validations/shippingmethods.post

  postShippingMethodService:
    name: ${self:custom.ow-package}/postShippingMethodService
    handler: lib/actions/shippingmethods.post

  validateDeleteShippingMethodService:
    name: ${self:custom.ow-package}/validateDeleteShippingMethodService
    handler: lib/validations/shippingmethods.del

  deleteShippingMethodService:
    name: ${self:custom.ow-package}/deleteShippingMethodService
    handler: lib/actions/shippingmethods.del
